# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c2e45d9d6d1cd2c4a2ef6676a862afcc289ec824992a9b7596c40353b10ffe388928d808dea96732a69c23c727285c93b2b35b4562933291e5533972fe748bf6

test:
  secret_key_base: 769eb80b997bb3f188c6b4fe6cb52866a5714c166d6558be2e5a0d2565b3934eddc886c5cde4e823576dd142072d770374465390fc4a749bf8d33e8edeb1695e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
